apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-collection-service
  namespace: data-collection
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/data-collection-SERVICE_ACCOUNT_ROLE
  labels:
    app: data-collection-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/external-secrets-operator-role
  labels:
    app: external-secrets-operator