apiVersion: v1
kind: Service
metadata:
  name: eda-ui-dataplatform-dsaas-svc
  namespace: eda-ui
  labels:
    app.kubernetes.io/name: eda-ui-dataplatform-dsaas-deploy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: eda-ui-dataplatform-dsaas-deploy
  ports:
    - name: svcui-port
      port: 80
      protocol: TCP
      targetPort: 80
    - name: svcui-sslport
      port: 443
      protocol: TCP
      targetPort: 80