apiVersion: v1
kind: Service
metadata:
  name: eda-services-dataplatform-dsaas-svc
  namespace: eda-services
  labels:
    app.kubernetes.io/name: eda-services-dataplatform-dsaas-svc
spec:
  selector:
    app.kubernetes.io/name: eda-services-dataplatform-dsaas-deploy
  ports:
  - name: http
    port: 8000
    targetPort: app-port
    protocol: TCP
  type: ClusterIP